"""update

Revision ID: 320eddec0fc8
Revises: 77d2b98f5731
Create Date: 2026-01-12 15:54:13.403607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320eddec0fc8'
down_revision: Union[str, Sequence[str], None] = '77d2b98f5731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_recipe_dish_servings_creator_published', 'recipes', ['dish_name', 'servings', 'created_by', 'is_published'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_recipe_dish_servings_creator_published', 'recipes', type_='unique')
    # ### end Alembic commands ###
