"""update recipe_version

Revision ID: 77d2b98f5731
Revises: 
Create Date: 2026-01-12 12:38:16.147622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d2b98f5731'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_scores', sa.Column('version_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'recipe_scores', 'recipe_versions', ['version_id'], ['version_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_scores', type_='foreignkey')
    op.drop_column('recipe_scores', 'version_id')
    # ### end Alembic commands ###
