"""change feedbacks table

Revision ID: 9c4790ab05e4
Revises: c49862faf9ac
Create Date: 2026-01-10 10:51:01.939520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4790ab05e4'
down_revision: Union[str, Sequence[str], None] = 'c49862faf9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('version_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('feedbacks_recipe_id_fkey'), 'feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'feedbacks', 'recipe_versions', ['version_id'], ['version_id'])
    op.drop_column('feedbacks', 'recipe_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('recipe_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.create_foreign_key(op.f('feedbacks_recipe_id_fkey'), 'feedbacks', 'recipes', ['recipe_id'], ['recipe_id'])
    op.drop_column('feedbacks', 'version_id')
    # ### end Alembic commands ###
