"""add approve in recipe version

Revision ID: cff1f63d475a
Revises: 95d9ba4c5732
Create Date: 2026-01-09 15:48:47.072923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff1f63d475a'
down_revision: Union[str, Sequence[str], None] = '95d9ba4c5732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_versions', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_versions', 'approved')
    # ### end Alembic commands ###
